### ISSUE TITLE
Add support for code examples

### ISSUE THREAD

**Issue by anandology** [pipalacademy/mkdocs-feather#1]
It should support including code examples using the following syntax.

<pre>
```{.feather .python}
print("hello, world!")
```
</pre>

The following things need to be added to the `mkdocs.yml` to enable this plugin.

```
plugins:
  - mkdocs-feather:
        server_url: https://feather.pipal.in/
```

## Tasks

- [x] create a python package
- [x] inject javascript and css files
- [x] inject codemirror files for python
- [x] provide option to specify the codemirror modes to enable
- [x] added feature.js with livecode integration
- [x] support customizing server_url

**Comment by anandology** [comment]
We may want to support extended configuration. for example:


When there are multiple servers for each runtime:

```
plugins:
  - mkdocs-feather:
        server_url: 
            default: https://feather.pipal.in/
            python: https://python-feather.pipal.in/
            go: https://go-feather.pipal.in/
        modes:
            c-joy: 
                runtime: cjoy
                syntax: c
```

This need not be part of this issue, but leaving as note so that it is tracked.

**Comment by anandology** [comment]
Done. currently supported config:

```
site_name: Python Tutorial

plugins:
  - feather:
      modes:
        - python
        - ruby
        - htmlmixed
      server_url: http://127.0.0.1:5000/
theme:
  name: material
```
